updates

diff --git a/charts/redis-dds/templates/configmap.yaml b/charts/redis-dds/templates/configmap.yaml
--- a/charts/redis-dds/templates/configmap.yaml
+++ b/charts/redis-dds/templates/configmap.yaml
@@ -74,48 +74,98 @@ data:
     redis-server /data/redis.conf --slave-announce-ip $MY_IP
 
   start-slave.sh: |
+
+    HEADLESS_SERVICE="{{ .Release.Name }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
+    REDIS_SERVICE="{{ .Release.Name }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
+
+    while false
+    do
+        myip=$(hostname -i)
+        if [[ -z "$(getent ahosts "$HEADLESS_SERVICE" | grep "^${myip}" )" ]]; then
+            echo "$HEADLESS_SERVICE does not contain the IP of this pod: ${myip}"
+            sleep 5
+            return 1
+        else
+            echo "$HEADLESS_SERVICE has my IP, continuing: ${myip}"
+            return 0
+        fi
+    done
+
+    # If we are the only host listed in the headless service, assume we are the only container up and running
+    if [[ -z "$(getent ahosts "$HEADLESS_SERVICE" | grep -v "^$(hostname -i)")" ]]; then
+        echo "$HEADLESS_SERVICE only contains my IP, assume I am a master pod"
+        export REDIS_REPLICATION_MODE="master"
+    else
+        echo "$HEADLESS_SERVICE contains my IP, assuming I am a slave pod"
+        export REDIS_REPLICATION_MODE="slave"
+    fi
+
+    if [[ "$REDIS_REPLICATION_MODE" = "master" ]]; then
+        echo "Starting as master node"
+        ARGS=""
+    else
+        echo "Starting as a slave node"
+
+        # Get current master
+        sentinel_info_command="redis-cli -h $REDIS_SERVICE -p {{ .Values.sentinel.service.port }} sentinel get-master-addr-by-name {{ .Release.Name }}"
+
+        export REDIS_SENTINEL_INFO=($($sentinel_info_command))
+        export REDIS_MASTER_HOST=${REDIS_SENTINEL_INFO[0]}
+        export REDIS_MASTER_PORT_NUMBER=${REDIS_SENTINEL_INFO[1]}
+
+        if [[ ! ($($sentinel_info_command)) ]]; then
+            # master doesn't actually exist, this probably means the remaining pods haven't elected a new one yet
+            # and are reporting the old one still. Once this happens the container will get stuck and never see the new
+            # master. We stop here to allow the container to not pass the liveness check and be restarted.
+            echo "Could not find the master from the existing sentinels, exiting"
+            exit 1
+        fi
+
+        echo "Discovered master: $REDIS_MASTER_HOST:$REDIS_MASTER_PORT_NUMBER"
+        ARGS="--slaveof $REDIS_MASTER_HOST $REDIS_MASTER_PORT_NUMBER"
+    fi
+
     # Update redis.conf with current password
     cp -f /redis-configs/redis.conf /data/redis.conf
     sed -i "s/ADMINPASS/$ADMINPASS/g" /data/redis.conf
     sed -i "s/MY_IP/$MY_IP/g" /data/redis.conf
 
-    echo "Trying to connect to: $REDIS_MASTER_HOST:$REDIS_MASTER_PORT_NUMBER"
-
     # Start redis-server
-    redis-server /data/redis.conf --slave-announce-ip $MY_IP --slaveof $REDIS_MASTER_HOST $REDIS_MASTER_PORT_NUMBER
+    redis-server /data/redis.conf --slave-announce-ip $MY_IP $ARGS
 
   start-sentinel.sh: |
 
     HEADLESS_SERVICE="{{ .Release.Name }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
     REDIS_SERVICE="{{ .Release.Name }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
 
-    count=0
-    until [ "$count" = "5" ]
+    while false
     do
         myip=$(hostname -i)
         if [[ -z "$(getent ahosts "$HEADLESS_SERVICE" | grep "^${myip}" )" ]]; then
             echo "$HEADLESS_SERVICE does not contain the IP of this pod: ${myip}"
-            count=$(( count + 1 ))
             sleep 5
+            return 1
+        else
+            echo "$HEADLESS_SERVICE has my IP, continuing: ${myip}"
+            return 0
         fi
-        echo "$HEADLESS_SERVICE has my IP: ${myip}"
-        count=5
     done
 
     # If we are the only host listed in the headless service, assume we are the only container up and running
     if [[ -z "$(getent ahosts "$HEADLESS_SERVICE" | grep -v "^$(hostname -i)")" ]]; then
+        echo "$HEADLESS_SERVICE only contains my IP, assume I am a master pod"
         export REDIS_REPLICATION_MODE="master"
     else
+        echo "$HEADLESS_SERVICE contains my IP, assuming I am a slave pod"
         export REDIS_REPLICATION_MODE="slave"
     fi
-
-    echo "Sentinel mode: $REDIS_REPLICATION_MODE"
 
     if [[ "$REDIS_REPLICATION_MODE" = "master" ]]; then
         export REDIS_MASTER_HOST="$(hostname -i)"
         export REDIS_MASTER_PORT_NUMBER="{{ .Values.redis.service.port }}"
     else
 
+        # Get current master
         sentinel_info_command="redis-cli -h $REDIS_SERVICE -p {{ .Values.sentinel.service.port }} sentinel get-master-addr-by-name {{ .Release.Name }}"
 
         export REDIS_SENTINEL_INFO=($($sentinel_info_command))
